### ISSUE TITLE
.NET framework version requirement

### ISSUE THREAD

**Issue by Kevin-Palmerini** [MechMindRobotics/mecheye_csharp_samples#19]
Hello everyone,
I have a question about the system software requirements in ordert to work with mech-eye and DL SDKs.
Based on the informations shared on the website( [Csharp MechEyeAPI](https://docs.mech-mind.net/latest/en-GB/MechEye/MechEyeAPI/Samples/Csharp/Csharp.html) ), to use the MechEye vision functions, .NET 4.8 is required.
With that version of .NET I could correctly use the API. 
Then I tried to build my project using .NET 4.7.2 only, but the build was unsuccessful due to "MechEyeApiNet -> mmind.apiSharp" incompatibility.
Is there a way to make it work with .NET 4.7.2?
Thank you so much!

**Comment by shuaidang** [comment]
Hello, 
the current version of the MechEye API only supports .NET 4.8. You can contact our technical support team, and we will provide you with a customized version of the DLL library file.
